
## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [2]:
import numpy as np
my_array = np.arange(10) # creo el array
print("El array resultante sería:")
print(my_array[::-2]) # hago slicing de todo el array saltando de dos en dos desde atrás 
                      # (se inicia al final y llega hasta el inicio)

El array resultante sería:
[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [3]:
print("El nuevo print del array sería:")
print(my_array[8:6:-1]) # se inicia en 8 y llegas antes del 6, en el 7, hacia detrás

El nuevo print del array sería:
[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [4]:
print("La secuencia es:")
print(my_array[2::-1]) # del 2 al final hacia detrás

La secuencia es:
[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [5]:
matriz4 = np.random.randint(21,size=(4,5)) # he cambiado el 20 por el 21, ya que con 20 iría de 1 al 19
print("La matriz4 es:")
print()
print(matriz4)
print()
print("La matriz4 invertida es:")
print()
inv4 = matriz4[::-1, ::-1] # para invertir elijo el orden inverso de las filas y el orden inverso de las columnas
print(inv4)

La matriz4 es:

[[ 6 20 19  7  7]
 [ 8  8 16  6 15]
 [ 6 15  2  3  2]
 [ 8 18  9  7  6]]

La matriz4 invertida es:

[[ 6  7  9 18  8]
 [ 2  3  2 15  6]
 [15  6 16  8  8]
 [ 7  7 19 20  6]]


In [6]:
# Así se invierten filas y columnas
seg_inversion = matriz4.T
print("La matriz que invierte filas y columnas es:")
print(seg_inversion)

La matriz que invierte filas y columnas es:
[[ 6  8  6  8]
 [20  8 15 18]
 [19 16  2  9]
 [ 7  6  3  7]
 [ 7 15  2  6]]


In [7]:
otra_inv = np.flip(matriz4)
print("Otra manera de invertir valores:")
print(otra_inv)

Otra manera de invertir valores:
[[ 6  7  9 18  8]
 [ 2  3  2 15  6]
 [15  6 16  8  8]
 [ 7  7 19 20  6]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [8]:
# Entiendo que el ejercicio pide crear una matriz de 2x2 a partir de la inv4, es decir, de la matriz invertida de la matriz4

matriz5 = inv4[:2, :2] # para seleccionar la cuadrícula superior izquierda, elijo de la primera fila a la segunda y de la primera
                       # primera columna a la segunda.
print("Obtengo una matriz de 2x2 a partir de inv4:")
print()
print(matriz5)

Obtengo una matriz de 2x2 a partir de inv4:

[[6 7]
 [2 3]]


## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [9]:
matriz6 = inv4[:2, :3] # parecido al anterior ejercicio. Elijo desde el inicio hasta la segunda fila y del inicio a la
                       # tercera columna
print("Obtengo una matriz de 2x3 a partir de inv4:")
print()
print(matriz6)

Obtengo una matriz de 2x3 a partir de inv4:

[[6 7 9]
 [2 3 2]]


## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [10]:
matriz7 = inv4[:3, :5] # parecido al anterior ejercicio. Elijo desde el inicio hasta la segunda fila y del inicio a la
                       # tercera columna
print("Obtengo una matriz de 3x5 a partir de inv4:")
print()
print(matriz7)

Obtengo una matriz de 3x5 a partir de inv4:

[[ 6  7  9 18  8]
 [ 2  3  2 15  6]
 [15  6 16  8  8]]


## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [11]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"]) # array original
mascara = (x == "Loro") # creo una variable máscara que busque valores iguales a "Loro"
xloro = x[mascara] # aplico la máscara al array x, y la guardo en un nuevo array
print("La primera posibilidad es utilizar máscara:")
print()
print(xloro) # imprimo el nuevo array

La primera posibilidad es utilizar máscara:

['Loro' 'Loro']


In [13]:
indice = np.where(x == "Loro") # busco los índices del array donde se encuentra la palabra Loro
xloro_a = x[indice] # extraigo los valores del array original en un nuevo array
print("La segunda opción sería con np.where():")
print()
print(xloro_a) # imprimo el nuevo array
        

La segunda opción sería con np.where():

['Loro' 'Loro']


In [12]:
loros = np.extract(x == "Loro", x)
print(loros)

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transfórmala en un array compuesto por 2 matrices de 5x2

In [14]:
secuencia = np.arange(20) # creo una secuencia de numeros del 0 al 19
print("La secuencia es:")
print()
print(secuencia) # imprimo la secuencia
print()
print("La secuencia con dos matrices de 5x2 es:")
print()
secuencia2 = secuencia.reshape(2,5,2) # la modifico en un array de dos matrices con 5 filas y 2 columnas
print(secuencia2)

La secuencia es:

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

La secuencia con dos matrices de 5x2 es:

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


## Ejercicio 10

Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [15]:
print("Este es un array de 10 ceros:")
print()
array10 = np.full((2,5), 0) # creo un array de ceros con 2 filas y 5 columnas
print(array10)
print()
print(f"Ocupa en memoria: {array10.nbytes} bytes") # obtengo los bytes que ocupa
print()
print("Si sustituyo el cuarto elemento por un uno, el array nuevo quedaría así:")
print()
array10_a = array10.copy() # hago una copia del array
array10_a[0][3] = 1 # en la fila 1, columna 4 pongo un 1
print(array10_a) # imprimo el nuevo array con 9 ceros y un 1

Este es un array de 10 ceros:

[[0 0 0 0 0]
 [0 0 0 0 0]]

Ocupa en memoria: 80 bytes

Si sustituyo el cuarto elemento por un uno, el array nuevo quedaría así:

[[0 0 0 1 0]
 [0 0 0 0 0]]


In [16]:
ceros = np.zeros(10)
print(ceros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Ejercicio 11

Crea un vector que vaya del 10 al 49

Inviértelo

In [17]:
vector = np.arange(10, 50) # creo el vector
print("El vector es:")
print()
print(vector) # lo imprimo
inv_vector = vector[::-1] # recorro el vector de fin a inicio
print()
print("El vector invertido es:")
print()
print(inv_vector)

El vector es:

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

El vector invertido es:

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [18]:
print(np.flip(vector))

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


## Ejercicio 12
Encuentra los índices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/) Encapsúlalo en una función, con un argumento de entrada de un vector.

In [19]:
vector12 = np.array([1,2,0,0,4,0])
print("Este es el vector:")
print()
print(vector12)
print()
output = np.where(vector12 != 0)[0] # con np.where obtengo un tupla con las posiciones de los elementos diferentes a 0.
                                    # Añado el [0] para que solo imprima el primer elemento de la tupla, que serían esas
                                    # posiciones.
print("Este es el vector con los índices que son diferentes a 0:")
print()
print(output) # imprimo las posiciones

# Me ha faltado encapsular la función

def indices(vector):
    output = np.where(vector12 != 0)[0]
    return output
print()
print("El resultado de la función es:")
indices(vector12)

Este es el vector:

[1 2 0 0 4 0]

Este es el vector con los índices que son diferentes a 0:

[0 1 4]

El resultado de la función es:


array([0, 1, 4])

## Ejercicio 13
Crea una matriz de números aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [22]:
matriz13 = np.random.randint(0, 80, size=(10,10)) # creo una matrix de 10x10 del 0 al 80
print("La matriz de núnmeros aleatorios de 10x10 es:")
print()
print(matriz13)
print()
print(f"El valor mínimo es: {matriz13.min()}") # obtengo el valor mínimo de la matriz
print()
print(f"El valor máximo es: {matriz13.max()}") # obtengo el valor máximo de la matriz

La matriz de núnmeros aleatorios de 10x10 es:

[[14 12 39 76 39 57 32 16 53 44]
 [31 45 55 71 75  9 56 37  2  5]
 [22 59 31 51 39 57 70 67 69 44]
 [50 75 12 33 71 61 44 41 33  2]
 [71 19 63 71 43  1  2 25 33  4]
 [64 33 55 53  5 77 62 20 29 70]
 [12 31  5 22 45 57 77  1 42 79]
 [64 49 29 59 28  3 16 20 11  2]
 [78 76 20 57 56 36 27 59 17 69]
 [50 18  5 45 70 34 52 73 40 27]]

El valor mínimo es: 1

El valor máximo es: 79


## Ejercicio 14
Crea un vector aleatorio de tamaño 30 y calcula su media

In [21]:
vector14 = np.random.rand(30) # creo un vector aleatorio de tamaño 30
print("El vector es:")
print()
print(vector14) # imprimo el vector
print()
print(f"La media del vector es: {vector14.mean()}") # calculo la media

El vector es:

[0.71069862 0.98596248 0.45684452 0.83481121 0.59005447 0.87370568
 0.73543728 0.23807119 0.88433495 0.72239541 0.03492682 0.62061431
 0.86279089 0.0866434  0.41125511 0.43819617 0.51293848 0.91925254
 0.27744581 0.80762764 0.68544367 0.16544871 0.65437459 0.76104608
 0.43735615 0.36072328 0.44688773 0.96928993 0.00134129 0.00397621]

La media del vector es: 0.5496631544604695


## Ejercicio 15
Crea un array cuadrado de 2D, con las dimensiones que quieras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [15]:
array15 = np.full((5,5), 1) # primero creo un array lleno de unos
print("Array de unos de 5x5:")
print()
print(array15)
print()
array15[1:-1, 1:-1] = 0 # sustituimos los unos por ceros con slicing
                        # los ceros van desde la segunda fila (posición 1) hasta la penúltima fila (-1)
                        # y también van desde la segunda columna (posición 1) a la penúltima (-1)
print("El array con ceros en el interior:")
print()
print(array15)


Array de unos de 5x5:

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]

El array con ceros en el interior:

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Ejercicio 16
Crea una matriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [16]:
# como en el ejercicio anterior, se puede partir de una matriz de 8x8 con ceros
# como el resultado final tiene que ser como un tablero de ajedrez, no se puede sustituir todos los impares por unos
# Dependerá de cada fila. En la fila uno sustituimos a partir de [1] de dos en dos
# En la fila dos sustituimos a partir del [0] de dos en dos
matriz16 = np.full((8,8), 0) # creo la matriz de ceros 8x8
print("Esta es la matriz de la que partimos:")
print()
print(matriz16) # imprimo la matriz de ceros
matriz16[::2, 1::2] = 1 # aqui voy a las filas 0, 2, 4 y 6 (::2) y pon un uno en la intersección con la columna 1, 3, 5 y 7 (1::2)     
matriz16[1::2, ::2] = 1 # aquí voy a las columnas 0, 2, 4 y 6 (::2) y pongo 1 en la intersección con las filas 1, 3, 5 y 7 (1::2)
print()
print("La matriz de ajedrez sería:")
print()
print(matriz16) # imprimo el ajedrez


Esta es la matriz de la que partimos:

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]

La matriz de ajedrez sería:

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 17
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [17]:
# La definición de esta función es que repite un array (A) un número x de veces (reps)
# numpy.tile(A, reps)
# Si nos fijamos en la solución anterior, se puede ver que la solución es una matriz que repite la matriz 0 1
#                                                                                                         1 0 
# Habrá que repetir la matriz pequeña cuatro veces en horizontal y cuatro veces en vertical

patron = np.array([[0,1], [1,0]])
print("El array pequeño a repetir es:")
print()
print(patron)
print()
matriz17 = np.tile(patron, (4,4)) # repito el patron 4 veces por fila y 4 veces por columna
print("El tablero de ajedrez es:")
print()
print(matriz17)

El array pequeño a repetir es:

[[0 1]
 [1 0]]

El tablero de ajedrez es:

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Ejercicio 18
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [28]:
matriz18 = np.random.randint(10, 20, (5,5))
print("La matriz aleatoria de 5x5 es:")
print()
print(matriz18)
media = matriz18.mean()

desv_est = matriz18.std()

matriz_media = matriz18 - media

matriz_normalizada = matriz_media / desv_est
print()
print("La matriz normalizada es:")
print()
print(matriz_normalizada)

La matriz aleatoria de 5x5 es:

[[11 14 19 17 14]
 [18 15 15 19 12]
 [10 16 12 17 13]
 [18 16 17 14 13]
 [11 18 16 13 17]]

La matriz normalizada es:

[[-1.5430335  -0.38575837  1.5430335   0.77151675 -0.38575837]
 [ 1.15727512  0.          0.          1.5430335  -1.15727512]
 [-1.92879187  0.38575837 -1.15727512  0.77151675 -0.77151675]
 [ 1.15727512  0.38575837  0.77151675 -0.38575837 -0.77151675]
 [-1.5430335   1.15727512  0.38575837 -0.77151675  0.77151675]]


## Ejercicio 19
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [ ]:
vector19 = np.arange(11) # creo la secuencia de números (vector)
print("El vector es:")
print(vector19)
print()
print("Ahora sustituimos del 3 al 8 por -1:") 
print()
vector19_a = np.where((vector19 >= 3) & (vector19 <= 8), -1, vector19) # sustituyo con np.where y doble condición
print(vector19_a)
print()
vector19_b = np.where((vector19 >= 3) & (vector19 <= 8), -vector19, vector19) # entiendo que negar significa cambiar el signo, con lo que hago el negativo de vector19
print("Entiendo que negar significa cambiar el signo:")
print()
print(vector19_b)


El vector es:
[ 0  1  2  3  4  5  6  7  8  9 10]

Ahora sustituimos del 3 al 8 por -1:

[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]

Entiendo que negar significa cambiar el signo:

[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
