![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [4]:
import numpy as np
print(np.__version__)

2.4.4


## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [6]:
my_array = np.arange(10)
print(my_array)
print(type(my_array))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [10]:
arraytrue = np.full((3,3), True)
print(arraytrue)
print(type(arraytrue))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
<class 'numpy.ndarray'>


## Ejercicio 4
Extrae todos los impares de `my_array`

In [12]:
impares = my_array[1::2]
print(impares)

[1 3 5 7 9]


## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [19]:
nuevo_array = []
for i in my_array:
    if i in impares:
        nuevo_array.append(-1)
    else:
        nuevo_array.append(i)

print(nuevo_array)

        

[np.int64(0), -1, np.int64(2), -1, np.int64(4), -1, np.int64(6), -1, np.int64(8), -1]


In [ ]:
# como me salía ese resultado raro arriba, he mirado que esto se debe a que mezclo listas y arrays
# la solución que he encontrado es convertir a int los elementos del array, con lo que así puedo
# ver los elementos como han quedado en el array de la sustitución

nuevo_array = []
for i in my_array:
    if i in impares:
        nuevo_array.append(-1)
    else:
        nuevo_array.append(int(i))

print(nuevo_array)

[0, -1, 2, -1, 4, -1, 6, -1, 8, -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [ ]:
nuevo_array = np.where(my_array % 2 != 0, -1, my_array) 

'''
He utilizado el método where, que no necesita de un bucle para hacer la sustitución.
Se invoca con np.where y consiste en tres parámetros:
    - El primero es la condición, en este caso que el elemento en cuestión sea impar, es decir, que su resto sea distinto de cero
    - El segundo es el valor que queremos sustituir (-1)
    - El tercero es donde queremos hacer la operación (en el array "nuevo_array")
'''

print(nuevo_array)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [ ]:
dos_dim = my_array.reshape(2,5)

'''
Para transformar un array de 10 elementos en dos dimensiones, el número de elementos debe ser igual.
En este caso, he utilizado 2 filas y 5 columnas, pero podría haber hecho 5 filas y dos columnas. 
Simplemente hay que utilizar el método reshape y especificar, entre los paréntesis, las filas y las columnas.
'''

print(dos_dim)

[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticalmente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [ ]:
a = np.arange(10).reshape(2,-1) # con el reshape 2, -1, le decimos a NumPy que cree dos filas como quiera de un array inicial de 0 a 9
b = np.repeat(1, 10).reshape(2,-1) # dos filas como quiera, de diez unos

print(a) # imprimo el array a
print("-" *60)
print(b) # imprimo el array b
print("-" *60)

# Para concatenar verticalmente uso np.concatenate((arrays en formato tupla), eje   )

print(np.concatenate((a,b))) # concateno verticalmente con el método concatenate
print("-" *60)

# También se puede utilizar np.vstack((arrays en tupla))

print(np.vstack((a,b))) # concateno verticalmente con el método vstack


[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------------------------------------
[[1 1 1 1 1]
 [1 1 1 1 1]]
------------------------------------------------------------
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]
------------------------------------------------------------
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [ ]:
a = np.arange(10).reshape(2,-1) # array del 0 al 9 en dos dimensiones
b = np.repeat(1, 10).reshape(2,-1) # array de diez unos en dos dimensiones
print(a) # imprimo el array a
print("-" *60)
print(b) # imprimo el array b
print("-" *60)
print(np.concatenate((a,b), axis=1)) # concateno horizontalmente con el método concatenate
print("-" *60)
print(np.hstack((a,b))) # concateno horizontalmente con el método hstack

[[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------------------------------------
[[1 1 1 1 1]
 [1 1 1 1 1]]
------------------------------------------------------------
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]
------------------------------------------------------------
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa la función `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [ ]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(a) # imprimo el array a
      print("-" *60)
print(b) # imprimo el array b
print("-" *60)

comunes = np.intersect1d(a,b) # intersect1d comprueba elementos comunes entre dos arrays
print(comunes) # imprimo los elementos comunes

[1 2 3 2 3 4 3 4 5 6]
------------------------------------------------------------
[ 7  2 10  2  7  4  9  4  9  8]
------------------------------------------------------------
[2 4]


## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [37]:
help(np.concatenate)

Help on _ArrayFunctionDispatcher in module numpy:

concatenate(arrays, /, axis=0, out=None, *, dtype=None, casting='same_kind')
    Join a sequence of arrays along an existing axis.

    Parameters
    ----------
    a1, a2, ... : sequence of array_like
        The arrays must have the same shape, except in the dimension
        corresponding to `axis` (the first, by default).
    axis : int, optional
        The axis along which the arrays will be joined.  If axis is None,
        arrays are flattened before use.  Default is 0.
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what concatenate would have returned if no
        out argument were specified.
    dtype : str or dtype
        If provided, the destination array will have this dtype. Cannot be
        provided together with `out`.

        .. versionadded:: 1.20.0

    casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
   

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento de `my_array`
3. Accede al último elemento de `my_array`
4. Imprime por pantalla los numeros del 1 al 7 de `my_array`

In [ ]:
my_array1 = np.arange(10) # creo el array de 0 a 9
print(my_array1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
pordiez = my_array1 * 10 # multiplico los elementos del array por diez
print(pordiez)

[ 0 10 20 30 40 50 60 70 80 90]


In [41]:
print(my_array[0]) # imprimo el primer elemento del array

0


In [42]:
print(my_array[-1]) # imprimo el último elemento del array

9


In [ ]:
print(my_array1[1:8]) # imprimo desde el índice 1 al índice 7

[1 2 3 4 5 6 7]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [46]:
my_matrix = np.array([[0,1,2],[3,4,5],[6,7,8]]) # creo una lista de tres listas, es decir, tres filas y tres columnas
print(my_matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [49]:
array14 = np.arange(1, 50, 3) # creo un array de 1 a 49, introduzco 50 por se queda uno antes del máximo, y de tres en tres
print(array14)

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49]


## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [ ]:
array15 = np.arange(4, 1, -0.25) # creo un array de 4 a 1 yendo hacia detrás en saltos de 0.25
print(array15)

[4.   3.75 3.5  3.25 3.   2.75 2.5  2.25 2.   1.75 1.5  1.25]


## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [53]:
array17 = np.random.randint(10, size=(4,1)) # creo un array aleatorio de 4x1
print(array17) # lo imprimo
print("-" * 60)
array17_a = array17.reshape(2,2) # lo cambio a uno de 2x2
print(array17_a)

[[5]
 [4]
 [3]
 [7]]
------------------------------------------------------------
[[5 4]
 [3 7]]


## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [56]:
array18 = np.random.randint(0, 11, size=(4,5,3)) # creo una secuencia aleatoria del 0 al 10 de 4 matrices, 5 filas y 3 columnas
print(array18)

[[[ 7  1  2]
  [ 8  0  1]
  [ 9  8  9]
  [10  8  7]
  [ 0  2  6]]

 [[ 4  5  3]
  [ 1  7  9]
  [ 1  0  3]
  [ 9  1  4]
  [10  1  9]]

 [[ 3  5 10]
  [ 5  0  0]
  [10  3  5]
  [10  6  7]
  [ 4  7  0]]

 [[ 2  9  0]
  [10  0  7]
  [10  8 10]
  [ 2  3  9]
  [ 7  2  4]]]


## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [61]:
array19 = np.full((10,1), False) # creo una matriz de 10 filas y 1 columna con False
print(array19)
print("-" * 60)
array19_a = array19.reshape(2,5) # transformo el array a uno de 2 filas y 5 columnas
print(array19_a)

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]
------------------------------------------------------------
[[False False False False False]
 [False False False False False]]


## Ejercicio 20
Dado el siguiente array

```Python
x = np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuánta es la longitud cada dimensión?

In [62]:
x = np.random.randint(10, 20, size = (5,2,6))
print(x)
print("-" * 60)
print(f"El array tiene {x.size} elementos.") # x.size calcula los elementos del array
print(f"El array tiene {x.ndim} dimensiones.") # x.ndim calcula el nº de dimensiones
print(f"Cada dimensión tiene una longitud de {x.shape}.") # x.shape calcula la longitud de las dimensiones

[[[18 11 11 18 14 15]
  [19 15 12 18 14 12]]

 [[16 17 12 12 11 10]
  [16 10 13 14 16 18]]

 [[11 19 19 19 18 15]
  [17 10 16 16 12 17]]

 [[12 16 17 16 15 15]
  [11 11 18 18 18 10]]

 [[14 16 12 19 16 18]
  [15 15 12 19 10 12]]]
------------------------------------------------------------
El array tiene 60 elementos.
El array tiene 3 dimensiones.
Cada dimensión tiene una longitud de (5, 2, 6).
